name: Build and Publish PyPI

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    tags:
      - 'v*'
jobs:
  build-and-publish:
    runs-on: windows-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mindm-mcp
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build twine

      - name: Build the package
        run: python -m build
  
      - name: Verify package
        run: twine check dist/*
      
      - name: Publish to PyPI
        run: twine upload --verbose --repository pypi dist/*

      - name: Create GitHub Release
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --title "${{ github.ref_name }}" --generate-notes
